#ifndef CYGONCE_PKGCONF_DEVS_GX_SERIAL_H
#define CYGONCE_PKGCONF_DEVS_GX_SERIAL_H
/*
 * File <pkgconf/devs_gx_serial.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGPKG_IO_SERIAL_GX 1
#define CYGPKG_IO_SERIAL_GX_SERIAL0 1
#define CYGDAT_IO_SERIAL_GX_SERIAL0_NAME "/dev/ser0"
#define CYGDAT_IO_SERIAL_GX_SERIAL0_BASE 0x00400000
#define CYGDAT_IO_SERIAL_GX_SERIAL0_BASE_0x00400000
#define CYGDAT_IO_SERIAL_GX_SERIAL0_BAUD 115200
#define CYGDAT_IO_SERIAL_GX_SERIAL0_BAUD_115200
#define CYGDAT_IO_SERIAL_GX_SERIAL0_IN_BUFSIZE 2048
#define CYGDAT_IO_SERIAL_GX_SERIAL0_IN_BUFSIZE_2048
#define CYGDAT_IO_SERIAL_GX_SERIAL0_OUT_BUFSIZE 0
#define CYGDAT_IO_SERIAL_GX_SERIAL0_OUT_BUFSIZE_0
#define CYGDAT_IO_SERIAL_GX_SERIAL0_BUFSIZE 2048
#define CYGDAT_IO_SERIAL_GX_SERIAL0_BUFSIZE_2048
#define CYGPKG_IO_SERIAL_GX_SERIAL1 1
#define CYGDAT_IO_SERIAL_GX_SERIAL1_NAME "/dev/ser1"
#define CYGDAT_IO_SERIAL_GX_SERIAL1_BASE 0x00401000
#define CYGDAT_IO_SERIAL_GX_SERIAL1_BASE_0x00401000
#define CYGDAT_IO_SERIAL_GX_SERIAL1_BAUD 115200
#define CYGDAT_IO_SERIAL_GX_SERIAL1_BAUD_115200
#define CYGDAT_IO_SERIAL_GX_SERIAL1_IN_BUFSIZE 2048
#define CYGDAT_IO_SERIAL_GX_SERIAL1_IN_BUFSIZE_2048
#define CYGDAT_IO_SERIAL_GX_SERIAL1_OUT_BUFSIZE 0
#define CYGDAT_IO_SERIAL_GX_SERIAL1_OUT_BUFSIZE_0
#define CYGDAT_IO_SERIAL_GX_SERIAL1_BUFSIZE 2048
#define CYGDAT_IO_SERIAL_GX_SERIAL1_BUFSIZE_2048
#define CYGPKG_IO_SERIAL_DSW_SERIAL 1
#define CYGDAT_IO_SERIAL_DSW_NAME "/dev/ser0"
#define CYGDAT_IO_SERIAL_DSW_BASE 0x00403000
#define CYGDAT_IO_SERIAL_DSW_BASE_0x00403000
#define CYGDAT_IO_SERIAL_DSW_BAUD 115200
#define CYGDAT_IO_SERIAL_DSW_BAUD_115200
#define CYGDAT_IO_SERIAL_DSW_IN_BUFSIZE 2048
#define CYGDAT_IO_SERIAL_DSW_IN_BUFSIZE_2048
#define CYGDAT_IO_SERIAL_DSW_OUT_BUFSIZE 0
#define CYGDAT_IO_SERIAL_DSW_OUT_BUFSIZE_0
#define CYGDAT_IO_SERIAL_DSW_BUFSIZE 2048
#define CYGDAT_IO_SERIAL_DSW_BUFSIZE_2048
#define CYGPKG_IO_SERIAL_GX_OPTIONS 1
#define CYGPKG_IO_SERIAL_GX_TESTING 1
#define CYGPRI_SER_TEST_CRASH_ID "gx3110"
#define CYGPRI_SER_TEST_TTY_DEV  "/dev/tty1"
#define CYGPRI_SER_TEST_SER_DEV "/dev/ser1"

#endif
