#ifndef CYGONCE_PKGCONF_HAL_CKMMU_CK610M_GX3201_H
#define CYGONCE_PKGCONF_HAL_CKMMU_CK610M_GX3201_H
/*
 * File <pkgconf/hal_ckmmu_ck610m_gx3201.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD 115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD_115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD 115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD_115200
#define CYGNUM_HAL_RTC_CONSTANTS 1
#define CYGNUM_HAL_RTC_NUMERATOR 1000000000
#define CYGNUM_HAL_RTC_NUMERATOR_1000000000
#define CYGNUM_HAL_RTC_DENOMINATOR 100
#define CYGNUM_HAL_RTC_DENOMINATOR_100
#define CYGNUM_HAL_RTC_PERIOD 400000
#define CYGNUM_HAL_RTC_PERIOD_400000
#define CYGNUM_HAL_BREAKPOINT_LIST_SIZE 25
#define CYGNUM_HAL_BREAKPOINT_LIST_SIZE_25
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS 1
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS_1
#define CYGSEM_HAL_USE_ROM_MONITOR CygMon
#define CYGSEM_HAL_USE_ROM_MONITOR_CygMon

#endif
